@GeneratePrism(io.avaje.jsonb.CustomAdapter.class)
@GeneratePrism(io.avaje.jsonb.Json.class)
@GeneratePrism(io.avaje.jsonb.Json.Import.class)
@GeneratePrism(io.avaje.jsonb.Json.Import.Imports.class)
@GeneratePrism(io.avaje.jsonb.Json.Alias.class)
@GeneratePrism(io.avaje.jsonb.Json.Creator.class)
@GeneratePrism(io.avaje.jsonb.Json.Ignore.class)
@GeneratePrism(io.avaje.jsonb.Json.Property.class)
@GeneratePrism(io.avaje.jsonb.Json.MixIn.class)
@GeneratePrism(io.avaje.jsonb.Json.Raw.class)
@GeneratePrism(io.avaje.jsonb.Json.SubTypes.class)
@GeneratePrism(io.avaje.jsonb.Json.SubType.class)
@GeneratePrism(io.avaje.jsonb.Json.Unmapped.class)
@GeneratePrism(io.avaje.jsonb.Json.Value.class)
@GeneratePrism(io.avaje.jsonb.Json.Serializer.class)
@GeneratePrism(io.avaje.jsonb.spi.MetaData.class)
@GeneratePrism(io.avaje.jsonb.spi.MetaData.JsonFactory.class)
package io.avaje.jsonb.generator;

import io.avaje.prism.GeneratePrism;
